global_defs {
        script_user root
        enable_script_security
}

vrrp_script check_pg_is_master {
        script "/etc/keepalived/allow_vip_check.sh"
        interval 3
        timeout 2
        fall 1
        rise 1
}

vrrp_instance PG_VIP {
        state BACKUP
        interface eth0
        virtual_router_id 97
        priority 254
        advert_int 1
        authentication {
                auth_type PASS
                auth_pass p@$$word
        }
        virtual_ipaddress {
                10.7.2.94/24
        }
        track_script {
                check_pg_is_master
        }
}
