global_defs {
        script_user root
        enable_script_security
}

vrrp_script check_pg_is_master {
        script "/etc/keepalived/pg_replication_role_check.sh"
        interval 3
        timeout 2
        fall 1
        rise 1
}

vrrp_instance PG_VIP {
        state MASTER
        interface eth1
        virtual_router_id 97
        priority 255
        advert_int 1
        authentication {
                auth_type PASS
                auth_pass p@$$word
        }
        virtual_ipaddress {
                192.168.56.100/24
        }
        track_script {
                check_pg_is_master
        }
}